# INTRODUCTION

<div style = "background-color:lightblue; color:green; font-size:20px; text-align:justify">The Google Play Store is one of the world's largest digital marketplaces, hosting millions of applications across diverse categories and serving billions of Android users. Understanding the characteristics of successful applications can provide valuable insights for developers and businesses seeking to improve user engagement and market performance. This dataset contains information on Google Play Store applications, including attributes such as category, rating, size, number of installs, reviews, price, and content rating. Through Exploratory Data Analysis (EDA), this project aims to uncover patterns, trends, and relationships among these features to better understand the factors that influence an app's popularity and user satisfaction.

CREDIT: L. Gupta, "Google Play Store Apps," Feb 2019. Available: https://www.kaggle.com/lava18/google-play-store-apps

# OBJECTIVES:

<div style = "background-color:lightblue; color:green; font-size:20px; text-align:justify">
<li>To analyze the distribution of applications across different categories on the Google Play Store.
<li>To identify trends and patterns in app ratings, reviews, installs, and pricing.
<li>To examine the relationship between app characteristics and their popularity among users.
<li>To compare the performance of free and paid applications across various metrics.
<li>To uncover actionable insights that can help developers make informed decisions when designing and marketing Android applications.

<div>

# 1. Getting Ready With Dataset

In [1]:
import numpy as np
import pandas as pd
import polars as pl

import matplotlib.pyplot as plt
import seaborn as sns
import seaborn.objects as so

In [10]:

data = pl.read_csv(
    "/home/kartika/Datasets/googleplaystore.csv", 
    schema_overrides={
        "Reviews": pl.String,
        "Price": pl.String,
        "Installs": pl.String
    }
)
data = data.to_pandas()

data["Price"] = data["Price"].str.replace("$", "", regex=False).str.strip()
data["Price"] = pd.to_numeric(data["Price"], errors="coerce")


data["Reviews"] = pd.to_numeric(data["Reviews"], errors="coerce")

data.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19M,"10,000+",Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14M,"500,000+",Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7M,"5,000,000+",Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25M,"50,000,000+",Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8M,"100,000+",Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

<div style = "background-color:lightblue; color:green; font-size:20px; text-align:justify">
Issue Identified: A column-shift anomaly was detected at row index 10474 (Life Made WI-Fi Touchscreen Photo Frame) due to a missing Category field. This shifted non-numeric strings into numerical columns (e.g., '3.0M' in Reviews, 'Everyone' in Price), causing schema parse failures.

Action Taken:

Overrode initial import schemas to ingest numeric target columns as raw strings.

Stripped currency formatting ($) and applied soft numeric coercion (pd.to_numeric(..., errors='coerce')) to turn misaligned strings into NaN values without interrupting pipeline execution.

Dropped the corrupted row to ensure dataset integrity across numeric analyses.

In [11]:
data.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38.0,53M,"5,000+",Free,0.0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4.0,3.6M,100+,Free,0.0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3.0,9.5M,"1,000+",Free,0.0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114.0,Varies with device,"1,000+",Free,0.0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307.0,19M,"10,000,000+",Free,0.0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10840 non-null  float64
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10841 non-null  object
 7   Price           10840 non-null  float64
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10840 non-null  object
 12  Android Ver     10840 non-null  object
dtypes: float64(3), object(10)
memory usage: 1.1+ MB

In [19]:
# check for each columns in excel

In [12]:
data.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              1
Size                 0
Installs             0
Type                 0
Price                1
Content Rating       1
Genres               0
Last Updated         0
Current Ver          1
Android Ver          1
dtype: int64

<div style = "background-color:lightblue; color:green; font-size:20px; text-align:justify">Rating columns has a lot of missing values, other few columns has one missing values which will be handled during their individual analysis.