<h3 style = "color:green">INTRODUCTION

<div style = "background-color:lightblue; color:green; font-size:20px; text-align:justify">
Netflix is one of the world's leading streaming platforms, offering a vast collection of movies and TV shows across different genres, languages, and regions. This dataset, sourced from TMDb (The Movie Database), contains detailed information about Netflix content, including titles, genres, release dates, ratings, and descriptions. The dataset has been cleaned and structured to ensure consistency, making it suitable for exploratory data analysis (EDA). Through EDA, we can gain insights into Netflix's content library, identify patterns in content production, and understand trends in genres, ratings, and release years.
</div>

<h3 style = "color:green">OBJECTIVES

<div style = "background-color:lightblue; color:green; font-size:20px; text-align:justify">
<ul>
<li>Analyze the distribution of movies and TV shows available on Netflix.
<li>Explore content trends across release years.
<li>Identify the most common genres and content categories.
<li>Examine the distribution of ratings and audience classifications.
<li>Investigate patterns in content duration and popularity-related attributes.
<li>Discover relationships between different content features and uncover key insights about Netflix's catalog.
<li>Generate findings that can support content recommendation and business decision-making.

</div>

<h3 style = "color:green">Getting Ready With Data

In [1]:
import numpy as np
import pandas as pd
import polars as pl

import matplotlib.pyplot as plt
import seaborn as sns
import seaborn.objects as so

In [ ]:
data = pl.read_csv('/home/kartika/Datasets/netflix_tv_shows_detailed_up_to_2025.csv')
data = data.to_pandas()
data.head()

   show_id     type              title  ... popularity vote_count vote_average
0    33238  TV Show        Running Man  ...   1929.898        187        8.241
1    32415  TV Show              Conan  ...   1670.580        229        7.035
2    37757  TV Show  MasterChef Greece  ...   1317.092          6        5.600
3    75685  TV Show         Prostřeno!  ...   1095.776          6        6.500
4    33847  TV Show           The Talk  ...    712.070         12        3.400

[5 rows x 16 columns]

In [3]:
data.tail()

       show_id     type  ... vote_count vote_average
15995   284892  TV Show  ...          0          0.0
15996   277665  TV Show  ...          0          0.0
15997   284972  TV Show  ...          1         10.0
15998   284613  TV Show  ...          0          0.0
15999   251815  TV Show  ...          0          0.0

[5 rows x 16 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       16000 non-null  int64
 1   type          16000 non-null  object
 2   title         16000 non-null  object
 3   director      5035 non-null   object
 4   cast          14843 non-null  object
 5   country       14203 non-null  object
 6   date_added    16000 non-null  object
 7   release_year  16000 non-null  int64
 8   rating        16000 non-null  float64
 9   duration      16000 non-null  object
 10  genres        15026 non-null  object
 11  language      16000 non-null  object
 12  description   12794 non-null  object
 13  popularity    16000 non-null  float64
 14  vote_count    16000 non-null  int64
 15  vote_average  16000 non-null  float64
dtypes: float64(3), int64(3), object(10)
memory usage: 2.0+ MB

In [5]:
data.isnull().sum()

show_id             0
type                0
title               0
director        10965
cast             1157
country          1797
date_added          0
release_year        0
rating              0
duration            0
genres            974
language            0
description      3206
popularity          0
vote_count          0
vote_average        0
dtype: int64

<div style = "background-color:lightblue; color:green; font-size:20px; text-align:justify">There are some missing values(blank values) in director, cast, contry, genres and description fields which will be handled during their respective analysis.

<div>

<h3 style = "color:green">Univariate Analysis

<h4 style = "color:green">1.